import { Poppins } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/side-menu";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  display: "swap",
});

export const metadata = {
  title: "Admin Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div className="h-12 flex items-center justify-center bg-white shadow-lg z-50">

        </div>
        <div className="flex transition-all duration-300 ease-in-out bg-[#f2F4F8] h-screen">
          <SideBar />
          <div
            id="main-container"
            className="flex-1 transition-all duration-300 ease-in-out p-4"
          >
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
